scuffed56/SCUFFED5.0

common/decisions/formNation.txt

- Added Balkans formable to Romania
- minor bug fixes

Minor fixes for form nations

---

common/ideas/_role_of_women.txt

-changed the output of women's auxiliary from 20% supply consumption to 5% while adding a 20% buff to supply hubs and railways.

TCDTF Womens auxilary

---

common/game_rules/00_game_rules.txt
common/on_actions/hosttool_on_actions.txt
common/scripted_guis/hosttool.txt
interface/hosttool.gui
localisation/english/horsttool_l_english.yml

-added a add 50 PP and a remove 50 PP button to the host tool
-added an option to make turkey or holand a host in the game rules

TCDTF Host Tool

---

common/decisions/formable_nation_decisions.txt
common/ideas/egypt.txt
common/ideas/portugal.txt
common/national_focus/FrenchIndochina.txt
common/national_focus/colombia.txt
common/national_focus/congo.txt
common/national_focus/egypt.txt
common/national_focus/malaysia.txt
common/national_focus/philippines.txt
common/national_focus/portugal.txt
common/national_focus/r56_gran_colombia_shared.txt
common/national_focus/r56_greece.txt
common/national_focus/saudi_arabia.txt

- Fixed the Cruiser bonuses so they actually work
- Added cruiser subs because they are in base game tree, but not in 56 tree.

TCDTF Focus Fixes and Balancing

---

common/buildings/00_buildings.txt
common/game_rules/00_game_rules.txt
common/ideas/r56i_laws_leadership.txt
common/ideas/r56i_laws_social.txt
common/scripted_diplomatic_actions/pay_civ_factory.txt
localisation/english/replace/r56_game_rules_l_english.yml

-rewrote civ button logic to prevent bugs/abuse
-removed ability to send civs to AI
-changed localization for game rules regarding Poland to make them clear
-changed the order of the game rules to put emphasis on the host tool
-you can now build aa in allies
-removed pp cost from leadership and social laws

Fullchord changes

---

common/ai_strategy_plans/POL_historical_strategy_plan.txt
common/ideas/poland.txt
common/national_focus/poland.txt
history/units/POL_1936_air_bba.txt

-fixed missing buffs
-changed focus path to include new focuses
-reduced polish starting air

TCDTF Poland

---

common/decisions/formNation.txt
common/national_focus/r56_greece.txt
events/r56_Greece.txt
events/r56_usa.txt
localisation/english/GRE_l_english.yml

Error Fixing/ bug fixing

---

common/decisions/HOL.txt
common/national_focus/netherlands_MtG.txt
events/MTG_Netherlands.txt

fixes decisions to unite the benelux, didn't add cores and the ai did not have a factor to accept
gave the focuses in the democratic path to give belgium and luxemborg the same buffs that netherlands gets

Benelux fix

---

common/units/infantry.txt
history/units/ITA_1936.txt
history/units/ITA_1936_nsb.txt

- Removed locked units for italy
- Debuffed paratroopers

Para Nerf and Italy units

---

common/technologies/MTG_naval_Support.txt

Adds naval gunnery "string" to technologies categories

Naval gunnery

---

common/game_rules/00_game_rules.txt

Makes sending dockyards enabled by default

dockyards enabled by default

---

common/national_focus/mali.txt
history/units/WLL_motor_cavalry.txt

- Prevented AI from doing the funny MALI focus
- Removed weird OOB errors from WLL_motor_cavalry

Mali fix + Wallonia

---

common/national_focus/flanders.txt
common/national_focus/quebec.txt
common/national_focus/wallonia.txt
localisation/english/QBC_l_english.yml

-Fixed the focuses that Quebec, Flanders, and Wallonia had to cause the game to crash by loading oob. 
-Uncommented out a Quebec focus and fixed localization involved

TCDTF Crashes

---

common/ideas/germany.txt
common/national_focus/germany.txt
localisation/english/GER_l_english.yml

germany aa/tanks

---

common/national_focus/germany.txt
common/national_focus/romania.txt

that one focus

---

common/ideas/japan.txt
common/national_focus/japan.txt
localisation/english/JAP_I_english.yml
localisation/english/JAP_l_english.yml

Turning lunge mines to a national spirit like we did with alot of the germany tree

lunge mines fix

---

common/technologies/infantry.txt

-Small tank stats on machine guns and flame thrower tech

---

common/national_focus/uk.txt

UK focus trees re added back in

---

common/decisions/GRE.txt
common/decisions/formNation.txt
common/ideas/_press.txt
common/ideas/brazil.txt
common/national_focus/brazil.txt
common/national_focus/greece.txt
common/national_focus/honduras.txt
common/national_focus/usa.txt

-Fixed Byzantium formable
-Base game Greece revert
-Brazil buffs
-Honduras bonuses
-USA bonuses
-Press Law balancing

TCDTF Fixes

---

common/ideas/ireland.txt
common/national_focus/ireland.txt

-Changed around some values and gfx for Ireland

TCDTF Ireland

---

common/decisions/formNation.txt
localisation/english/form_interface_l_english.yml
localisation/english/form_nation_tooltips_l_english.yml

-portobrazil
-francospain
-west rome is formable

-formables

---

common/national_focus/r56_mexico.txt

mex hot fix

---

history/countries/CHI - China.txt
history/countries/MEX - Mexico.txt
history/countries/NEP - Nepal.txt

- Mexico was messed up because the port of older tree.
- Nepal 3 research slots
- China 3 research slots

TCDTF Research Slot

---

common/national_focus/belgium.txt
events/BEL_events.txt

- Tried to fix Belgium event that fires to Netherlands
- Added factories to their no focus industry tree

TCDTF Belgium

---

common/national_focus/r56_gen_shared.txt

set it specifically moving cubas instead of everyone elses, what ever he did moved austrias as well so i had to move it again

-tcdtf fixing jonahs industrial boom move

---

common/ideas/_economic.txt

TCDTF Fixes bug

---

common/decisions/formNation.txt
common/decisions/formable_nation_decisions.txt
common/game_rules/000_eu4_like_ideas_game_rules.txt
common/scripted_guis/hosttool.txt

- Removes North America formable
- Fixes host tool, now annexes troops
- Changes EU4 ideas so they are now only allowed to cost 100, removes game rule to change the cost

Tcdtf final changes

---

common/ai_focuses/MEX.txt
common/decisions/r56_SOV_decisions.txt
common/decisions/r56_prospecting.txt
common/dynamic_modifiers/r56_GER.txt
common/ideas/belgium.txt
common/ideas/british_raj.txt
common/ideas/czechoslovakia.txt
common/ideas/germany.txt
common/ideas/japan.txt
common/ideas/r56_poland.txt
common/ideas/spain_republic.txt
common/national_focus/belgium.txt
common/national_focus/germany.txt
common/national_focus/germany_standard.txt
common/national_focus/r56_greece.txt
common/national_focus/r56_mexico.txt
common/national_focus/spain.txt
common/on_actions/r56_on_actions.txt
common/opinion_modifiers/r56_opinion_modifiers.txt
localisation/english/GER_l_english.yml
localisation/english/POL_l_english.yml
localisation/english/r56_tooltips_l_english.yml

-Czech bug fixing for events, and fixes nerf so Czech players can actually paly the game
- Overhauls Spanish Focus tree with old create character issues across the board
- Fixes more bugs found in Sprain tree
- Fixes Bugs found in Mexico's ai
- Fixes bugs found in Belgium, British raj, japan, and opinion modifiers for Belgium.
- Adds in Broken Dynamic modifiers for Germany, and overhauls them to make them work.
- Fixes broken idea for Poland that now works again.

Czech event bugs

---

common/decisions/RAJ.txt
common/decisions/r56_generic_decisions.txt
common/ideas/british_raj.txt
common/national_focus/r56_india.txt

- Changed focus times, touched up events, and reworked some decisions to make 56 India more viable of a nation

TCDTF 56 India

---

common/country_leader/r56_CAN_traits.txt
common/decisions/categories/mal_decision_categories.txt
common/decisions/mal_trade_decisions.txt
common/ideas/algeria.txt
common/ideas/indonesia.txt
common/ideas/r56_canada.txt
common/ideas/switzerland.txt
common/national_focus/FrenchIndochina.txt
common/national_focus/algeria.txt
common/national_focus/ethiopia.txt
common/national_focus/france.txt
common/national_focus/horn_of_africa.txt
common/national_focus/indonesia.txt
common/national_focus/malaysia.txt
common/national_focus/r56_canada.txt
common/national_focus/siam.txt
common/national_focus/switzerland.txt
common/units/equipment/modules/00_ship_modules.txt
events/r56_canada.txt
history/countries/SWI - Switzerland.txt
localisation/english/focus_l_english.yml

-Rebalances, Siam, Malay, IndoChina, Dutch East Indies, Algeria, Ethiopia, Aussa, 
-Mass fixes for these countries, fixes bugs, fixes old techs, and fixes weird long focuses and make longer focuses better

Minor country rework

---

common/country_leader/r56_companies_traits.txt
common/script_enums.txt
common/technologies/r56_vechicles.txt
common/units/equipment/motorized.txt

-Fixes Crashes Relating to rocket arty

TCDTF Fixing Crashes

---

common/units/equipment/infantry.txt

TCDTF Inf IC

---

common/ideas/r56_generic.txt

-Exile laws improved so it is now not just a straight debuff to exiled countries, makes exile countries games playable

TCTDF Exile laws

---

common/national_focus/denmark.txt

- Changed around some focus tree times

TCDTF Denmark

---

common/abilities/generic_leader_abilities.txt
common/modifiers/00_static_modifiers.txt
common/occupation_laws/occupation_laws.txt
common/resistance_compliance_modifiers/compliance_modifiers.txt
common/resistance_compliance_modifiers/resistance_modifiers.txt

-Changes how compliance and resistance works
-Compliance: reworks the gains from compliance so now it is far more worthwhile to invest into compliance and to have better long term gains vs outright coring states.
Resistance: events for resistance are back. Has resistance grows, events will fire as well as the dynamic modifiers are fixed to work now. 
Occupation laws: Changes all occupation laws to be better and have more trade offs per tier, and to work better with Eu4 ideas in  mind each one has more flavor and trade offs. 
-General abilities
-Fixes Three general abilities to actually work again, so they are not locked behind strange requirements that made no sense. This should help out low supply areas, office more variety to the ability system. Also Staff office plan was nerfed from …

Occupation laws, and compliance update

---

common/national_focus/soviet.txt
events/r56_Poland.txt
localisation/english/POL_l_english.yml
localisation/english/r56_SOV_l_english.yml

-Adds in missing Polish events from 56. (THIS MASSIVELY HELPS OUT AGAINST PLAYER POLANDS)
-Adds in missing Local
-Alt hist russia P.2 reduces more time on their focuses, as their tree is long and can cuck russia due to their tree being too long

Sov alt hist branch p2

---

common/buildings/00_buildings.txt
common/characters/NOR.txt
common/ideas/norway.txt
common/ideas/r56i_laws_gender.txt
common/ideas/r56i_laws_social.txt
common/national_focus/greece.txt
common/national_focus/norway.txt
common/national_focus/r56_scandinavia_shared.txt
common/technologies/industry.txt
common/technologies/r56e_etax.txt
events/NaW_Norway.txt
history/countries/DEN - Denmark.txt
history/countries/NOR - Norway.txt

- SRD First Tech is instant
- Added Research slot to Scandi Nations, so they start with 4
- Reverted the Dispersed Industry nerf, and buffed Concentrated
- Norway balancing

TCDTF Changes

---

common/decisions/ETH.txt

-Updates ethopian choices to be quicker cheaper and also you can do that all at once now, but still have tons of consumer goods cost f ra while

TCDTF ETH Descs

---

common/decisions/formNation.txt
common/national_focus/r56_ethiopia.txt

-Ethiopia tree made to be more playable, touch ups for factory counts and focus dates, railway reworks to be actually a thing. 
-Ethiopia formable made to be accomplishable reverted to old formable 
-Italian east africa now has empire of the lion formable

TCDTF Ethiopia

---

common/ideas/r56_generic.txt
common/intelligence_agency_upgrades/intelligence_agency_upgrades.txt
common/modifiers/00_static_modifiers.txt
common/occupation_laws/occupation_laws.txt
common/operations/00_operations.txt
localisation/english/replace/vanilla_modifiericons_l_english.yml

-Last update of resistance, Fixes ai explosions
-Ai no longer suffers resistance or compliance issues. -Resistance has been fixed due to bugs from AI
-Laws updated to combat resistance growth
-ai no longer can take no garrison

TCDTF Resistance Update

---

common/ideas/germany.txt
common/ideas/romania.txt
common/ideas/zzz_generic.txt
common/national_focus/germany.txt
common/national_focus/romania.txt
history/units/ROM_civil_war_monarchist.txt

-Germany nerfs to Rocketry
-Rebalances German PP gains
-Updates Romania civil war to make it easier
-Updates looks to Romania Focus tree layout
-Romania Facist Path is better now

Germany fixes

---

common/ideas/r56_denmark.txt
common/ideas/r56_finland.txt
common/ideas/r56_iceland.txt
common/ideas/r56_norway.txt
common/ideas/r56_sweden.txt

fixes ideas. moved old ideas to r56 files as a seperate file

scandi ideas fixed

---

common/on_actions/r56_focus_tree_selection_on_actions.txt

56 russia on action was still here for some reason

-TCDTF stops 56 ideas from popping up

---

common/national_focus/germany.txt

-They had so many air bonuses it is crazy

TCDTF German Air

---

common/ideas/china.txt
common/national_focus/china_nationalist.txt

-China focus for civ eco has proper requirements
-China eco laws now have proper levels to allow to swap to civ eco in exchange for 450 pp (price doesnt change to 2000 when going from reduced to war reduced anymore) -AI china now dominions warlords to garantee they are dragged into chinese united front (not tibet)

-TCDTF china fix

---

common/national_focus/uk.txt
history/countries/CZE - Czechoslovakia.txt
history/countries/FRA - France.txt
history/countries/POL - Poland.txt
history/countries/USA - USA.txt

- Removed starting guarantees
- Removed Imperial Federation Focus

TCDTF Guarantees and Imp Fed

---

common/national_focus/korea.txt

these divs crashes player game when hovering them

-tcdtf korea commie civil war game crash divs

---

common/national_focus/japan.txt

Removes japs ability to faction

TCDTF Japanese Cheese

---

common/ideas/colombia.txt
localisation/english/COL_l_english.yml

TCDTF Colombia

---

common/ai_strategy_plans/ROM_alternate_strategy_plans.txt
common/ai_strategy_plans/ROM_historical_strategy_plan.txt
common/decisions/GEN_army.txt
common/decisions/categories/GEN_army.txt
common/ideas/GEN_army.txt
common/ideas/austria.txt
common/ideas/ethiopia.txt
common/ideas/mongolia.txt
common/ideas/romania.txt
common/ideas/saudi_arabia.txt
common/ideas/south_africa.txt
common/ideas/yugoslavia.txt
common/national_focus/GEN_army.txt
common/national_focus/canada.txt
common/national_focus/romania.txt
common/national_focus/uk.txt
common/national_focus/yugoslavia.txt
localisation/english/GEN_ARMY_l_english.yml
localisation/english/MON_l_english.yml

- Added Romania Army Tree
- Fixed the errors that were associated with the tree

TCDTF Romania Army 

---

common/ideas/france.txt
common/national_focus/france.txt
localisation/english/FRA_l_english.yml

-Focus time adjustments as it was way too long
-Swapped research slot and nuke research
-Added 2 more mainland development focuses
-Allowed continuing more focuses while capitulated

-Further france advancements

---

common/decisions/Ireland_decisions.txt
common/national_focus/czechoslovakia.txt
common/national_focus/finland.txt

Czech nerfs, Finland Demo Fix. Ireland FIx

Czech tree

---

common/technologies/land_doctrine.txt

TCDTF Asym Rework

---

common/national_focus/r56_manchukuo.txt
localisation/english/MAN_l_english.yml

-Manchu national government works properly
-Manchu able to destroy opium plants if japan nonaligned tree

manchu fix

---

common/decisions/SOV.txt

Fixes typo in soviets

---

common/country_leader/00_traits.txt
common/decisions/MTG_congress.txt
common/ideas/peace_training.txt
common/national_focus/czechoslovakia.txt
common/national_focus/hungary.txt
common/national_focus/usa.txt
common/technologies/industry.txt

- Removed the 9 month lock on reestablish the gold standard
- Nerfed ideology advisors
- Fixed infrastructure decision on USA so it doesn't overstack anymore
- Jim Crow Focus doesn't require divisions in the southern states
- Peacetime training has a little bit of military xp
- Czech infrastructure focus nerfed
- Hungary moved factories from one focus and put it to another and changed some times

Tcdtf America

---

common/national_focus/hungary.txt

- Added a steel focus to Hungary

TCDTF Hungary Steel Focus

---

common/national_focus/r56_australia.txt

- now requires 2/3 instead of all 3

tcdtf australia bottom focus
